### ISSUE TITLE
Error on install: "from rpy2.robjects.numpy2ri import numpy2ri" results in "ImportError: cannot import name 'numpy2ri'"

### ISSUE THREAD

**Issue by tpham2654** [KwatME/ccal#16]
This import statement line of `compute_information_coefficient.py`:
`from rpy2.robjects.numpy2ri import numpy2ri`

Results in this error:

```
Processing /home/computer/CCAL_Examples.v2/CCAL_Examples/ccal
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-be7ypfis-build/setup.py", line 3, in <module>
        from ccal import VERSION
      File "/tmp/pip-be7ypfis-build/ccal/__init__.py", line 81, in <module>
        from .compute_information_coefficient import compute_information_coefficient
      File "/tmp/pip-be7ypfis-build/ccal/compute_information_coefficient.py", line 3, in <module>
        from rpy2.robjects.numpy2ri import numpy2ri
    ImportError: cannot import name 'numpy2ri'
```
This was on a fresh install of Ubuntu 18.04.  

I managed to get around it by changing it to:
`import rpy2.robjects.numpy2ri as numpy2ri` in `compute_information_coefficient.py`.  No idea what the effects are on the program but ccal can be installed and imported as usual afterwards.

**Comment by KwatME** [comment]
Ok. Thanks for the update @tpham2654 :)
